write Greeter, GreeterTest, and makefile. So far unable to pass test.
JaysGitLab/cs-5666-greeting-bclinthall pull request #2
Opened 2017-01-31 14:46 UTC by bclinthall

Well, `java Greeter` successfully prints "Hello, World!" to the console.  However, following the "write the test first" advice, I wrote a test too.  But I fail the test with this message: 
```
org.junit.ComparisonFailure: failure, should be equal to "Hello, World!" expected:<Hello, World![]> but was:<Hello, World![
]>
```
I am puzzled.  Any help would be welcome.

2017-02-01 03:43 UTC, fenwickjb commented
expected:<Hello, World![]> but was:<Hello, World![
]>

The assertEquals is using the brackets< > to enclose and better show you your string. For example if a string has one space or two is hard to "see" but using these enclosing brackets would help.

The [ ] symbols are showing you the difference part between expected and actual. Expected the string to end, but the actual has a newline at the end of the string.

2017-02-01 03:46 UTC, fenwickjb requested changes

2017-02-01 03:46 UTC, fenwickjb commented on GreeterTest.java
> +        System.setOut(null);
This "breaks" System.out for any subsequent use.  Each test should set up data it needs, run the test, then restore everything to the way it was before.

2017-02-01 04:12 UTC, bclinthall commented
Using the explanation from @fenwickjb , I determined that what was actually gleaned from System.out included a line break at the end. So I trimmed the result before comparing to "Hello, World!". Since this modification, the program passes the test.  Further, in order to restore state prior to testing, I stored a reference to System.out before modification, and then set System.out to that origin state after testing.  As far as I can tell, by doing this I have restored the system to its pre-testing state.

2017-02-03 03:17 UTC, fenwickjb approved these changes

2017-02-03 11:47 UTC, merged